name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Pull latest Docker image
        working-directory: ~/url-shortener
        run: docker-compose pull

      - name: Restart containers
        working-directory: ~/url-shortener
        run: |
          docker-compose up -d --remove-orphans
          docker system prune -f

      - name: Check container status
        working-directory: ~/url-shortener
        run: docker-compose ps

      - name: View app logs
        working-directory: ~/url-shortener
        run: docker-compose logs --tail=50 app

